### ISSUE TITLE
Changer le profil, régime/j'aime/je ne peux pas)

### ISSUE THREAD

**Issue by YounesAbdennadher** [otakedev/ceihm-groupe-7#29]
Tasks :
- Créer la navbar en haut de l'écran d'accueil pour y mettre le bouton de profil
- Créer le bouton changer le profil dans la bar du haut
- Créer les pages de modif de profil dans un composant tabs

**Comment by JasonHaenlin** [comment]
![image](https://user-images.githubusercontent.com/19989504/106379370-c88a5b00-63ab-11eb-9ac2-ab678361e363.png)
