### ISSUE TITLE
Page de profil : La snackbar empêche de sélectionner le menu "Mes choix"

### ISSUE THREAD

**Issue by YounesAbdennadher** [otakedev/ceihm-groupe-7#34]
Lorsqu'on retire un produit du profil, la snackbar de confirmtion reste à l'écran trop longtemps et empêche de sélectionner "Mes choix" lorsqu'on l'onglet est baissé. 
Un bouton OK sur la snackbar pour la faire disparaitre plus vite serait souhaitable.

**Comment by JasonHaenlin** [comment]
Je vois le problème mais peut-être pas comme tu le décris pour le résoudre
